# Generated by Django 3.1.4 on 2021-01-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='My Blog', max_length=255),
        ),
    ]
