# Generated by Django 3.1.4 on 2021-01-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theBlog', '0004_auto_20210105_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
