# Generated by Django 3.1.4 on 2021-01-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theBlog', '0007_auto_20210106_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click the link above to read the blog....', max_length=255),
        ),
    ]
