# Generated by Django 3.1.4 on 2021-01-06 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theBlog', '0011_auto_20210106_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fb_url',
            new_name='facebook_url',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='web_url',
            new_name='website_url',
        ),
    ]
